config/routes.rb
HnClone::Application.routes.draw do
  get "sessions/new"

  root :to => 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in"  => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "log_in" => "sessions#create", :as => "sessions"

  resources :links do
    resources :comments
  end
  resources :votes#should this be out here?
  resources :users

  get "/links/:link_id/comments/:parent_id/new" => "comments#new", :as => "new_comment_reply"
  post "/votes/:object_type/:object_id" => "votes#create", :as => "object_votes"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :link_id, :user_id, :parent_id, :vote_count
  belongs_to :link
  belongs_to :user
  has_many :comments, :as => :object
  validates :body, :presence => true

  def editable?
    Time.now - created_at <= 900
  end

  # def vote_counter
  #   Vote.find_all_by_object_id(id).count #TODO: also add type=Link
  # end

  def self.parse_comments!(link_id, order_by)
    collection = []
    comments = ordered_comments(link_id, order_by)
    comments.each do |comment|
      if comment.parent_id == nil
        collection << comment
        children_comments = Comment.find_all_by_parent_id(comment.id)
        collection << children_comments if children_comments.count > 0
      end
    end
    collection
  end

  def self.update_votes
    comments = Comment.all
    comments.each { |comment| comment.update_attributes(:vote_count => Vote.find_all_by_object_id(comment.id).count) }
  end

  def collected_votes
    Vote.find_all_by_object_id(id)
  end

  private

  def self.ordered_comments(link_id, order_by)
    if (order_by)
      comments = Comment.order("#{order_by} DESC")
    else
      comments = Comment.order('created_at DESC')
    end
    comments.find_all_by_link_id(link_id)
  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    Comment.update_votes
    @link = Link.find_by_id(params[:link_id])
    @comment = Comment.new
    #@comments = Comment.find_all_by_link_id(params[:link_id])

    @nested_comments = Comment.parse_comments!(params[:link_id], params[:order_by])
    #@nested_comments.page(params[:page]).per(20)
  end

  def create
    @link = Link.find_by_id(params[:link_id])
    @comment = Comment.new(params[:comment])
    if @comment.save
      @link.increment!(:comment_count)
      redirect_to link_comments_path(@link), :notice => "Comment created!"
    else
      render "index"
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    @link = @comment.link
    if @comment.user.id == session[:user_id]
      if @comment.editable?
        @user = @comment.user
      else
        redirect_to link_comments_path(@link), alert: "Comment editing period has ended."
      end
    else
      redirect_to link_comments_path(@link), alert: "You are not authorized to edit this comment."
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @link = @comment.link
    @comment.update_attributes(params[:comment])
    redirect_to link_comments_path(params[:link_id]), :notice => "Comment updated!"
  end

  # This action makes the form to create a new comment reply, and a parent_id is required.
  # To make a new comment, see "create" action above.
  def new
    @parent_comment = Comment.find(params[:parent_id])
    @link = @parent_comment.link
    @comment = Comment.new
  end

  # def destroy
  #  @comment = Comment.find(params[:id])
  #   if @comment.user.id == session[:user_id]
  #     @comment.destroy
  #     redirect_to link_comments_path(params[:link_id])
  #   else
  #     redirect_to link_comments_path(params[:link_id]), alert: "You are not authorized to edit this link."
  #   end
  # end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for [@link, @comment], :html => { :class => 'form-horizontal' } do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h3>Comment is invalid</h3>
      <ul>
        <% for message in @comment.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :comment, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_area span4', :rows => 10 %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
    <%= f.hidden_field :link_id, :value => @link.id %>
    <% if @parent_comment %>
      <%= f.hidden_field :parent_id, :value => @parent_comment.id %>
    <% end %>
    <%= f.submit nil, :class => 'btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                links_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<!-- <div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize %></h2>
</div> -->


<p>
  <% if @current_user %>
    <span class="spread-word">
      <%= link_to_if votable?(@link),"<i class=\"icon-thumbs-up\"></i>".html_safe,
        object_votes_path(@link.class, @link.id),
        :method => :post %>
    </span>
  <% end %>


  <%= link_to @link.title, @link.url %>
</p>

<p class="indent">
    <%= pluralize(@link.vote_count, 'pt') %> 
  <span class="spread-word">            
    <%= " | " %>
  </span>
    <%="by: #{@link.user.username} " %>
  <span class="spread-word">            
    <%= " | " %>
  </span>
    <%= "#{time_ago_in_words(@link.created_at)} ago" %>
  <span class="spread-word">            
    <%= " | " %>
  </span> 
    <%= link_to "#{@link.comment_count} comments", link_comments_path(@link) %>
</p>

<% if session[:user_id] %>
  <%= render 'form' %>
<% end %>

<div class="sort_links">
  <p> 
    <%= "sort by:  " %>
    <span class="spread-word">
    <%= link_to "popular", {:controller => "comments", :action => "index", :order_by => "vote_count"} %>
    <%= " | " %>
    <%= link_to "recent", {:controller => "comments", :action => "index", :order_by => "created_at"} %>
  </span>
  </p>
</div>

<% if @nested_comments %>
  <% @nested_comments.each do |comment| %>
    <% if comment.is_a? Array %>
      <% comment.each do |child_comment| %>
        <div class="nested-comment">
          <p>
            <% if @current_user %>
              <span class="spread-word">
                <%= link_to_if votable?(child_comment), "<i class=\"icon-thumbs-up\"></i>".html_safe,object_votes_path(child_comment.class, child_comment.id), :method => :post %>
              </span>
            <% end %>
            <%= "by #{child_comment.user.username}" %>
            <span class="spread-word">
              <%= " | " %>
            </span>
            <%= "#{time_ago_in_words(child_comment.created_at)} ago" %>
          </p>
          <p>
            <span class="indent"><%= child_comment.body %></span>
          </p>
          <p>
            <% if session[:user_id] == child_comment.user.id and child_comment.editable? %>
              <%= link_to "Edit", edit_link_comment_path(@link, child_comment) %>
            <% end %>
          </p>
        </div>
      <% end %>
    <% else %>
      <div class="comment">
        <p>
          <% if @current_user %>
            <span class="spread-word">
              <%= link_to_if votable?(comment),
                         "<i class=\"icon-thumbs-up\"></i>".html_safe, object_votes_path(comment.class, comment.id),
                         :method => :post %>
            </span>
          <% end %>
          <%= "by #{comment.user.username}" %> 
          <span class="spread-word"><%= " | " %></span>
          <%= "#{time_ago_in_words(comment.created_at)} ago" %> 
        </p>

        <div class="indent">
        <p>
          <%= comment.body %>
        </p>

        <p>
          <small><%= link_to "Reply", new_comment_reply_path(@link, comment.id) %></small>
          <% if session[:user_id] == comment.user.id and comment.editable? %>
              <small><%= link_to "Edit", edit_link_comment_path(@link, comment) %></small>
          <% end %>
        </p>
      </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h2>Add Comment Reply</h2>
</div>

<table class="table table-striped">
  <tbody>
    <tr>
      <td>
          <div class="span2">
              <small><%= "by #{@parent_comment.user.username} | #{time_ago_in_words(@parent_comment.created_at)}" %> ago</small>
              <br />
          </div>
          <div class="span5"><%= @parent_comment.body %></div>
      </td>
    </tr>
  </tbody>
</table>

<%= render :partial => 'form' %>