config/routes.rb
HnClone::Application.routes.draw do
  get "sessions/new"

  root :to => 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in"  => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "log_in" => "sessions#create", :as => "sessions"

  resources :links do
    resources :comments
  end
  resources :votes#should this be out here?
  resources :users

  get "/links/:link_id/comments/:parent_id/new" => "comments#new", :as => "new_comment_reply"
  post "/votes/:object_type/:object_id" => "votes#create", :as => "object_votes"

end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt

  attr_accessible :email, :password_digest, :username, :password_confirmation, :password, :karma
  has_secure_password
  has_many :links
  has_many :comments

  validates :password_digest, :presence => true, :on => :create
  validates :email, :username, :presence => true
  validates :username, :email, :uniqueness => true

  def password=(new_password)
    logger.info("------------ new password -----------")
    logger.info(new_password)
    @password = Password.create(new_password)
    self.password_digest = @password
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'password_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'password_field' %>
    </div>
  </div>

  <div class="form">
    <%= f.submit nil, :class => 'btn btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/_form_sign.html.erb
<%= form_tag sessions_path do %>
  <p>
    <%= label_tag :username %>
    <%= text_field_tag :username, params[:email] %>
  </p>
  <p>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
  </p>
  <%= submit_tag "Log In", :class => 'btn' %>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:username) %></th>
      <th><%= model_class.human_attribute_name(:password_digest) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.email %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h3><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h3>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:username) %>:</strong></dt>
  <dd><%= @user.username %></dd>
  <dt><strong><%= model_class.human_attribute_name(:password_digest) %>:</strong></dt>
  <dd><%= @user.password_digest %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>