config/routes.rb
HnClone::Application.routes.draw do
  get "sessions/new"

  root :to => 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in"  => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "log_in" => "sessions#create", :as => "sessions"

  resources :links do
    resources :comments
  end
  resources :votes#should this be out here?
  resources :users

  get "/links/:link_id/comments/:parent_id/new" => "comments#new", :as => "new_comment_reply"
  post "/votes/:object_type/:object_id" => "votes#create", :as => "object_votes"

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :title, :url, :user_id, :comment_count, :points

  validates :title, :url, :presence => true
  validates :url, :uniqueness => true
  has_many :comments
  has_many :votes, :as => :object
  belongs_to :user

  def collected_votes
    Vote.find_all_by_object_id(id)
  end

  # def vote_count
  #   @vote_count ||= votes.count
  # end

  def vote_count
    Vote.find_all_by_object_id(id).count #TODO: also add type=Link
  end

  def calc_points
    time = (Time.now - created_at)/3600
    points = (vote_count / time*5).ceil
  end

  def self.update_points
    links = Link.all
    links.each { |link| link.update_attributes(:points => link.calc_points) }
  end

  def self.per_page
    20
  end

  # def link_votable?(current_user_id)
  #   (current_user_id != self.user_id) && (self.collected_votes.all? { |vote| vote.user_id != current_user_id })
  # end

end

# Use this to have Faker generate fake data
# 100.times do
#   link = Link.new(:title => Faker::Lorem.sentence(7), :url => Faker::Internet.url, :user_id => 1)
#   link.save
# end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def index
    Link.update_points
    if (params[:order_by])
      all_links = Link.order("#{params[:order_by]} DESC")
    else
      all_links = Link.order('points DESC')
    end
    @links = all_links.page(params[:page]).per(Link.per_page)
    if (params[:page])
      @page_offset = (params[:page].to_i - 1) * Link.per_page
    else
      @page_offset = 0
    end
  end

  def new
    @link = Link.new
    @user = User.find_by_id(session[:user_id])
  end

  def create
    @link = Link.new(params[:link])
    @user = User.find_by_id(session[:user_id])
    if @link.save
      redirect_to root_path, :notice => "Link created!"
    else
      render 'new'
    end
  end

  def edit
    @link = Link.find(params[:id])
    if @link.user.id == session[:user_id]
      @user = @link.user
    else
      redirect_to root_path, alert: "You are not authorized to edit this link."
    end
  end

  def update
    @link = Link.find(params[:id])
    @link.update_attributes(params[:link])
    redirect_to root_path
  end

  def destroy
    @link = Link.find(params[:id])
    if @link.user.id == session[:user_id]
      @link.destroy
      redirect_to root_path
    else
      redirect_to root_path, alert: "You are not authorized to edit this link."
    end
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for @link, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @link.errors.any? %>
    <div class="error_messages">
      <h3>Form is invalid</h3>
      <ul>
        <div class="alert alert-error">
        <% for message in @link.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
        </div>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field input-xxlarge' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.hidden_field :user_id, :value => @user.id %>
    <%= f.submit nil, :class => 'btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                links_path, :class => 'btn' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<%- model_class = Link -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/links/index.html.erb
<%- model_class = Link -%>

<!-- <div class="sort_links">
  <p> 
    <%= "sort by:  " %>
    <span class="spread-word">
    <%= link_to "popular", {:controller => "links", :action => "index", :order_by => "points"} %>
    <%= " | " %>
    <%= link_to "recent", {:controller => "links", :action => "index", :order_by => "created_at"} %>
  </span>
  </p>
</div> -->
  <div class="sort_links">
    <p> 
      <%= "sort by:  " %>
      <span class="spread-word">
      <%= link_to "popular", {:controller => "links", :action => "index", :order_by => "points"} %>
      <%= " | " %>
      <%= link_to "recent", {:controller => "links", :action => "index", :order_by => "created_at"} %>
    </span>
    </p>
  </div>
 
  <% @links.each_with_index do |link, index| %>
    <div class="data-link">
      <p>
        <span class="spread-word">
          <%= "#{index + 1 + @page_offset}." %>
          <% if @current_user %>
            <%= link_to_if votable?(link), "<i class=\"icon-thumbs-up\"></i>".html_safe,
                  object_votes_path(link.class, link.id), :method => :post %>
          <% end %>
        </span>

        <%= link_to link.title, link.url %>

        <% if session[:user_id] == link.user.id %>  
            <span class="spread-word">
              |
              <%= link_to "edit", edit_link_path(link.id) %>
              |
              <%= link_to "delete", link_path(link),
                      :method => :delete,
                      :data => { :confirm => t('.confirm',
                                 :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
            </span>
        <% end %>
      </p>
      <div class="indent">
        <p>
            <%= pluralize(link.vote_count, 'pt') %>
          <span class="spread-word">            
            <%= " | " %>
          </span>
            <%="by: #{link.user.username} " %>
          <span class="spread-word">            
            <%= " | " %>
          </span>
            <%= "#{time_ago_in_words(link.created_at)} ago" %>
          <span class="spread-word">            
            <%= " | " %>
          </span> 
            <%= link_to "#{link.comment_count} comments", link_comments_path(link) %>
        </p>

  <!--         <% if session[:user_id] == link.user.id %>
                <%= link_to "<i class=\"icon-pencil\"></i>".html_safe,
                        edit_link_path(link.id), :class => 'btn btn-mini' %>
                <%= link_to "<i class=\"icon-remove\"></i>".html_safe,
                        link_path(link),
                        :method => :delete,
                        :data => { :confirm => t('.confirm',
                                   :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
   -->  
        </p>

      </div>
    </div>
  <% end %>



<%= paginate @links %>

app/views/links/new.html.erb
<%- model_class = Link -%>
<div class="page-header">
  <h3>Submit Something Cool</h3>
</div>
<%= render :partial => 'form' %>

app/views/links/show.html.erb
<%- model_class = Link -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @link.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @link.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @link.user_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              links_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_link_path(@link), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              link_path(@link),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>