config/routes.rb
HnClone::Application.routes.draw do
  get "sessions/new"

  root :to => 'links#index'

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in"  => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  post "log_in" => "sessions#create", :as => "sessions"

  resources :links do
    resources :comments
  end
  resources :votes#should this be out here?
  resources :users

  get "/links/:link_id/comments/:parent_id/new" => "comments#new", :as => "new_comment_reply"
  post "/votes/:object_type/:object_id" => "votes#create", :as => "object_votes"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "hacker newbs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">hacker newbs</a>
          <div class="container nav-collapse">
            <ul class="nav">
                <% if session[:user_id] %>
                  <li><%= link_to "<i class=\"icon-plus\"></i>".html_safe+"New",
                              new_link_path %></li>
                  <li><%= link_to "Log Out", log_out_path %></li>
                <% else %>
                  <li><%= link_to "Sign Up", sign_up_path %></li>
                  <li><%= link_to "Log In", log_in_path %></li>
                <% end %>
              </li>
            </ul>
            <% if session[:user_id] %>
              <ul class="nav pull-right">
                <p class="navbar-text"><span class="spread-word"><%= "#{User.find(session[:user_id]).username} | Karma:#{User.find(session[:user_id]).karma}" %></span></p>
              </ul>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div><!--/row-->

        <div class="row"><br /></div>

      <footer>
        <p>&copy; Brent & Julie 2012</p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>

  </body>
</html>